apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-app
  template:
    metadata:
      labels:
        app: crashloop-app
    spec:
      containers:
      - name: crashloop-container
        image: busybox:stable
        command: ["sh", "-c", "exit 1"]